# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stephen Amaza | Personal Website
email: steveamaza@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Official website of Stephen Amaza, entrepreneur extraordinaire.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://steveamaza.com" # the base hostname & protocol for your site
twitter_username: steveamaza
github_username:  steveamaza

# Build settings
markdown: kramdown


exclude: [
  .git,
  .gitignore,
  .sass-cache,
  package.json,
  gulpfile.js,
  node_modules,
  bower_components,
  bower.json,
  .nojekyll,
  '**/*.log'
]

# Site environment overrode in _config.dev.yml
env: production
